### ISSUE TITLE
[request]Please Make This a Library!!!

### ISSUE THREAD

**Issue by sinadarvi** [trikita/talalarmo#17]
plz make this as library so we can use it in our project as a component!!!

**Comment by wooseong** [comment]
plz make this as library so we can use it in our project as a component!!

**Comment by wooseong** [comment]
plz make this as library so we can use it in our project as a component!!!

**Comment by xeruf** [comment]
what?

**Comment by sinadarvi** [comment]
Hi,
I think we should close this issue after 3 years. thanks.
